# Generated by Django 5.2.6 on 2025-12-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_bookingrequest_updated_at_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE booking_app_bookingrequest SET status = 'scheduled' WHERE status = 'accepted';",
            reverse_sql="UPDATE booking_app_bookingrequest SET status = 'accepted' WHERE status = 'scheduled';"
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
