# Generated by Django 5.2.6 on 2025-12-09 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_alter_bookingrequest_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingrequest',
            unique_together=set(),
        ),
    ]
