# Generated by Django 5.2.7 on 2025-12-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
