# Generated by Django 5.2.7 on 2025-10-14 17:02

import django.db.models.deletion
import profile_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, help_text='Upload a profile picture (max 5MB, JPEG/PNG/GIF/WebP only)', null=True, upload_to='avatars/', validators=[profile_app.models.validate_image_size, profile_app.models.validate_image_format])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
