# Generated by Django 5.2.7 on 2025-10-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_businessprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprofile',
            old_name='postal_code',
            new_name='zip_code',
        ),
    ]
