# Generated by Django 5.2.7 on 2025-10-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_rename_postal_code_businessprofile_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='updated_at',
        ),
    ]
