# Generated by Django 5.2.7 on 2025-10-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_remove_businessprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload business logo (max 5MB recommended)', max_length=200, null=True, upload_to='business_logo/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
