# Generated by Django 5.2.7 on 2025-10-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_businessprofile_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload business logo (recommended <5MB)', max_length=200, null=True, upload_to='business_logo/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
