# Generated by Django 5.2.7 on 2025-10-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thryve_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='swap_for',
            field=models.TextField(blank=True, null=True),
        ),
    ]
