# Generated by Django 5.2.7 on 2025-10-18 13:43

import thryve_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thryve_app', '0002_listing_budget_listing_swap_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a listing image (max 5MB, JPEG/PNG/GIF/WebP only)', null=True, upload_to='listings/', validators=[thryve_app.models.validate_listing_image_size, thryve_app.models.validate_listing_image_format]),
        ),
    ]
