# Generated by Django 5.2.7 on 2025-11-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thryve_app', '0003_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='subcategory',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('tools_equipment', 'Tools & Equipment'), ('raw_materials', 'Raw Materials'), ('services', 'Services'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
