# Generated by Django 5.2.7 on 2025-11-02 10:30

import django.db.models.deletion
import thryve_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thryve_app', '0004_listing_subcategory_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a listing image (max 5MB, JPEG/PNG/GIF/WebP only)', upload_to='listings/', validators=[thryve_app.models.validate_listing_image_size, thryve_app.models.validate_listing_image_format])),
                ('is_main', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='thryve_app.listing')),
            ],
            options={
                'ordering': ['-is_main', 'uploaded_at'],
            },
        ),
    ]
