# Generated by Django 5.2.6 on 2025-11-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thryve_app', '0005_remove_listing_image_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]