# Generated by Django 5.2.7 on 2025-11-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thryve_app', '0006_connection_connectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message with the connection request', null=True),
        ),
    ]