# Generated by Django 5.2.6 on 2025-11-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thryve_app', '0006_listing_date'),
        ('thryve_app', '0007_connectionrequest_message'),
    ]

    operations = [
    ]
